using linkedList;
linked linkedlist = new linked();
linkedlist.Add(56);
linkedlist.AddOne(70);
int a = linkedlist.search(56);
linkedlist.incert(a + 2, 30);
int b = linkedlist.search(30);
linkedlist.incert(b + 2, 40);
linkedlist.Show();
linkedlist.delete(40);
linkedlist.Show();
Console.WriteLine( "size of the list : {0}", linkedlist.size());
linkedlist.removeLast();